<?php

namespace ContainerTK8SZmd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_AltchaService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'contao.altcha' shared service.
     *
     * @return \Contao\CoreBundle\Altcha\Altcha
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Altcha/Altcha.php';

        return $container->services['contao.altcha'] = new \Contao\CoreBundle\Altcha\Altcha(($container->privates['contao.repository.altcha'] ?? $container->load('getContao_Repository_AltchaService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $container->getEnv('APP_SECRET'), 'SHA-256', 100000, 86400);
    }
}
