<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdhhxxf\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdhhxxf/Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRdhhxxf.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\ContainerRdhhxxf\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \ContainerRdhhxxf\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => 'Rdhhxxf',
    'container.build_id' => 'd86fc54c',
    'container.build_time' => 1725263783,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdhhxxf');
