services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lupcom\ContaoMemberNewsfeedBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'