<?php

namespace ContainerRdhhxxf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P4DRd9S_Contao_Fragment_Contao_FrontendModule_TwoFactorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private '.service_locator.p4DRd9S.contao.fragment._contao.frontend_module.two_factor' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return ($container->privates['.service_locator.p4DRd9S'] ?? $container->load('get_ServiceLocator_P4DRd9SService'))->withContext('contao.fragment._contao.frontend_module.two_factor', $container);
    }
}
