<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTK8SZmd\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTK8SZmd/Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTK8SZmd.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTK8SZmd\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false);
}

return new \ContainerTK8SZmd\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer([
    'container.build_hash' => 'TK8SZmd',
    'container.build_id' => '77a0b160',
    'container.build_time' => 1725263782,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTK8SZmd');
